spring.application.name=taskmaster

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=TaskMaster

info.app.version=1.0

info.app.author=Shubhek Sam
